[package]
name = "vips-test"
version = "0.1.0"
authors = ["renatomoitinho <renatomoitinhodias@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libvips = "1.1.5"
